AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hogwarts-notifications-service

  SAM template for the Hogwarts Notifications Service

Globals:
  Function:
    Timeout: 3
    LoggingConfig:
      LogFormat: JSON

Resources:
  CreateNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create-notification/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        CreateNotificationApi:
          Type: Api
          Properties:
            Path: /notifications
            Method: post

Outputs:
  CreateNotificationApi:
    Description: API Gateway endpoint URL for the create notification function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/notifications"

  CreateNotificationFunctionArn:
    Description: ARN of the create notification Lambda function
    Value: !GetAtt CreateNotificationFunction.Arn

  CreateNotificationFunctionIamRole:
    Description: IAM role created for the create notification function
    Value: !GetAtt CreateNotificationFunctionRole.Arn